import assert from "node:assert/strict";
import test from "node:test";
import { refreshEnumProvenance, renderEnums } from "../src/schema/core/classTool.js";

const banner = "// Generated by format-carbon carbon-class --emit-enums from schema enums.json.\n";
const body = `export const Effect = Object.freeze({
  Wireframe: 0,
  Solid: 1,
});

export const Font = Object.freeze({
  SMALL: 0,
  LARGE: 2,
});
`;
const source = banner + "\n" + body;
const records = [
    { name: "Font", qualifiedName: "Font", source: "blue/include/Renderer.h", line: 19,
        values: [{ name: "SMALL", value: 0 }, { name: "LARGE", value: 2 }] },
    { name: "Effect", qualifiedName: "IRenderer::Effect", ownerClass: "IRenderer",
        source: "blue/include/Renderer.h", line: 129,
        values: [{ name: "Wireframe", value: 0 }, { name: "Solid", value: 1 }] }
];
const mismatch = { code: "enum-provenance-mismatch" };

test("provenance refresh validates owned legacy exports without changing their bodies or records", () =>
{
    const snapshot = structuredClone(records);
    const result = refreshEnumProvenance(source, records);
    assert.equal(result, banner
        + "// Source: blue/include/Renderer.h:129 (IRenderer::Effect)\n"
        + "// Source: blue/include/Renderer.h:19 (Font)\n\n" + body);
    assert.equal(result.slice(result.indexOf("export const")), body);
    assert.equal(refreshEnumProvenance(result, records), result);
    assert.deepEqual(records, snapshot);
});

test("provenance refresh preserves CRLF executable bytes and replaces obsolete source citations", () =>
{
    const original = (banner + "// Source: old/include/Renderer.h:1 (Font)\n\n" + body).replace(/\n/g, "\r\n");
    const result = refreshEnumProvenance(original, records);
    assert.equal(result.slice(result.indexOf("export const")), body.replace(/\n/g, "\r\n"));
    assert.doesNotMatch(result, /old\/include/);
    assert.equal(refreshEnumProvenance(result, records), result);
});

test("ordinary enum emission retains ownership filtering and its exact JS and TS output", () =>
{
    const js = "export const Font = Object.freeze({\n  SMALL: 0,\n  LARGE: 2,\n});\n";
    const ts = "export interface FontEnum\n{\n  readonly SMALL: 0;\n  readonly LARGE: 2;\n}\n\n"
        + "export type FontValue = FontEnum[keyof FontEnum];\n\n"
        + "export const Font: FontEnum = Object.freeze({\n  SMALL: 0,\n  LARGE: 2,\n});\n";
    assert.equal(renderEnums(records, { js: true }), banner + "\n" + js);
    assert.equal(renderEnums(records, { js: true, header: false }), js);
    assert.equal(renderEnums(records), banner + "\n" + ts);
    assert.equal(renderEnums(records, { header: false }), ts);
    assert.equal(renderEnums([records[1]], { js: true }), banner + "\n");
});

test("provenance requires an exact export set, including duplicate and renamed export rejection", () =>
{
    assert.throws(() => refreshEnumProvenance(source, records.slice(0, 1)), mismatch);
    assert.throws(() => refreshEnumProvenance(source, [...records, {
        ...records[0], name: "Other", qualifiedName: "Other"
    }]), mismatch);
    assert.throws(() => refreshEnumProvenance(source.replace("export const Font", "export const Other"), records), mismatch);
    assert.throws(() => refreshEnumProvenance(source.replace("export const Font", "export const Effect"), records), mismatch);
});

test("identical values cannot disambiguate two native enums with the same exported name", () =>
{
    const ambiguous = { ...records[1], qualifiedName: "IOtherRenderer::Effect", ownerClass: "IOtherRenderer",
        source: "blue/include/OtherRenderer.h" };
    assert.throws(() => refreshEnumProvenance(source, [...records, ambiguous]), /ambiguous enum provenance for Effect/);
});

test("complete generated-body validation rejects value, member and order drift", () =>
{
    for (const altered of [
        source.replace("Solid: 1", "Solid: 4"),
        source.replace("Solid: 1", "SOLID: 1"),
        source.replace("  Solid: 1,\n", ""),
        source.replace("  Solid: 1,", "  Solid: 1,\n  Extra: 2,"),
        source.replace("  Wireframe: 0,\n  Solid: 1,", "  Solid: 1,\n  Wireframe: 0,")
    ]) assert.throws(() => refreshEnumProvenance(altered, records), mismatch);
    assert.throws(() => refreshEnumProvenance(source, [records[0], {
        ...records[1], values: [{ name: "Wireframe", value: 0 }, { name: "Solid", value: "1" }]
    }]), mismatch, "schema string values are not coerced into numeric values");
});

test("unparsed code and declaration variants are rejected rather than silently retained", () =>
{
    for (const altered of [
        source + "runSomething();\n",
        source + "export { Font as Alias };\n",
        source.replace("export const Effect", 'import "./start.js";\nexport const Effect'),
        source.replace("export const Effect", "const helper = 1;\nexport const Effect"),
        source.replace("Object.freeze({", "customFreeze({"),
        source.replace("Solid: 1", "Solid: computeValue()"),
        source.replace("Solid: 1", "['Solid']: 1"),
        source.replace("  Solid: 1,", "  Solid: 1,\n  Solid: 1,"),
        source.replace("  Solid: 1,", "  Solid: 1, // maintained change"),
        source.replace("export const Font", "export const Font: FontEnum")
    ]) assert.throws(() => refreshEnumProvenance(altered, records), mismatch);
});

test("maintained source, unsupported headers and empty input are rejected", () =>
{
    assert.throws(() => refreshEnumProvenance(body, records), mismatch);
    assert.throws(() => refreshEnumProvenance(source.replace(banner, "// Maintained module.\n"), records), mismatch);
    assert.throws(() => refreshEnumProvenance(banner + "// Other comment.\n\n" + body, records), mismatch);
    assert.throws(() => refreshEnumProvenance(banner + "// Source: old.h\u2028runSomething();\n\n" + body, records), mismatch);
    assert.throws(() => refreshEnumProvenance(source, []), mismatch);
    assert.throws(() => refreshEnumProvenance(null, records), mismatch);
});

test("source-qualified record validation rejects incomplete or unsafe citations", () =>
{
    for (const patch of [
        { qualifiedName: undefined }, { qualifiedName: "Other" }, { qualifiedName: "Bad\nName" },
        { source: undefined }, { source: "" }, { source: "/native/Header.h" },
        { source: "C:/native/Header.h" }, { source: "../Header.h" }, { source: "blue\\Header.h" },
        { source: "blue/Header.h\n// hidden" }, { source: "blue/Header.h\u2028runSomething()" },
        { line: 0 }, { line: 1.5 }, { line: undefined }
    ]) assert.throws(() => refreshEnumProvenance(source, [{ ...records[0], ...patch }, records[1]]), mismatch);
});

test("invalid schema member records cannot be used to certify an existing body", () =>
{
    for (const values of [
        [{ name: "SMALL", value: NaN }], [{ name: "SMALL", value: -0 }], [{ name: "SMALL", value: undefined }],
        [{ name: "SMALL", value: {} }], [{ name: "SMALL", value: 0 }, { name: "SMALL", value: 0 }],
        [{ name: "BAD NAME", value: 0 }], [{ name: "__proto__", value: 0 }], [null]
    ]) assert.throws(() => refreshEnumProvenance(source, [{ ...records[0], values }, records[1]]), mismatch);
});

test("provenance rejects reserved strict module bindings as export names", () =>
{
    for (const name of [
        "await", "let", "arguments", "eval", "yield", "implements", "interface", "package",
        "private", "protected", "public", "static", "class", "const", "enum", "default",
        "true", "false", "null", "import", "export", "with", "return"
    ])
    {
        const record = { name, qualifiedName: name, source: "blue/include/Binding.h", line: 1,
            values: [{ name: "VALUE", value: 0 }] };
        const text = banner + `\nexport const ${name} = Object.freeze({\n  VALUE: 0,\n});\n`;
        assert.throws(() => refreshEnumProvenance(text, [record]), mismatch, name);
    }
});

test("reserved member keys remain legal and contextual words remain valid bindings", () =>
{
    const keys = ["default", "await", "let", "arguments", "eval", "static", "class"];
    for (const name of ["async", "of", "get", "set"])
    {
        const record = { name, qualifiedName: name, source: "blue/include/Binding.h", line: 1,
            values: keys.map((key, value) => ({ name: key, value })) };
        const declaration = `export const ${name} = Object.freeze({\n`
            + keys.map((key, value) => `  ${key}: ${value},`).join("\n") + "\n});\n";
        const result = refreshEnumProvenance(banner + "\n" + declaration, [record]);
        assert.equal(result.slice(result.indexOf("export const")), declaration);
        assert.equal(refreshEnumProvenance(result, [record]), result);
    }
});
