import assert from "node:assert/strict";
import test from "node:test";
import { refreshEnumRegistrations, renderEnums } from "../src/schema/core/classTool.js";

const banner = "// Generated by format-carbon carbon-class --emit-enums from schema enums.json.\n\n";
const source = banner + `export const Mode = Object.freeze({
  Off: 0,
  On: 1,
  Alias: 1,
});

export const Other = Object.freeze({
  A: 8,
  B: 16,
});
`;
const records = [
    {name: "Mode", qualifiedName: "Owner::Mode", ownerClass: "Owner", source: "core/Owner.h", line: 9,
        values: [{name: "Off", value: 0}, {name: "On", value: 1}, {name: "Alias", value: 1}]},
    {name: "Other", qualifiedName: "Other", source: "core/Other.h", line: 12,
        values: [{name: "A", value: 8}, {name: "B", value: 16}]}
];
const registrations = [{exportName: "Mode", name: "trinity.Owner.Mode", definition: {
    source: "core/Owner.h", family: "domain", line: 19, exposedName: "Modes", exposure: 2,
    chooserSource: "core/Owner_Blue.cpp:10",
    chooser: [{name: "On first", member: "Alias", description: "Alias spelling"}, {name: "Off next", member: "Off"}]
}}];
const mismatch = {code: "enum-registration-mismatch"};

test("registration refresh preserves legacy exports, aliases and distinct metadata provenance", () =>
{
    const snapshot = structuredClone({records, registrations});
    const result = refreshEnumRegistrations(source, records, registrations);
    assert.match(result, /export const Mode = \{/);
    assert.match(result, /export const Other = Object\.freeze\(\{/);
    assert.match(result, /blueEnums\.Create\("trinity.Owner.Mode", Mode,/);
    assert.match(result, /"line": 19/);
    assert.match(result, /"name": "On first",\n\s+"value": 1/);
    assert.match(result, /"name": "Off next",\n\s+"value": 0/);
    assert.equal(refreshEnumRegistrations(result, records, registrations), result);
    assert.equal(refreshEnumRegistrations(source.replace("});\n\nexport", "});\n\n\nexport"), records, registrations), refreshEnumRegistrations(source, records, registrations));
    assert.deepEqual({records, registrations}, snapshot);
    assert.doesNotMatch(renderEnums(records, {js: true}), /export const Mode/,
        "ordinary emission must still exclude class-owned enums");
});

test("registration refresh retains header citations and CRLF on repeated refresh", () =>
{
    const original = source.replace("\n\n", "\n// Source: core/Owner.h:9 (Owner::Mode)\n\n").replaceAll("\n", "\r\n");
    const result = refreshEnumRegistrations(original, records, registrations);
    assert.match(result, /Owner::Mode\)\r\n\r\n/);
    assert.doesNotMatch(result, /(?<!\r)\n/);
    assert.equal(refreshEnumRegistrations(result, records, registrations), result);
    assert.equal(refreshEnumRegistrations(source.replace("});\n\nexport", "});\n\n\nexport"), records, registrations), refreshEnumRegistrations(source, records, registrations));
});

test("emitted registration executes after declarations and retains the exported identity", async () =>
{
    const registryImport = "data:text/javascript," + encodeURIComponent(`export const blueEnums = {
        Create(name, values, definition) {
            if (values.On !== definition.chooser[0].value) throw new Error("chooser mismatch");
            Object.defineProperty(values, Symbol.for("test.enum"), {value: name});
            return Object.freeze(values);
        }
    };`);
    const result = refreshEnumRegistrations(source, records, registrations, {registryImport});
    const module = await import("data:text/javascript," + encodeURIComponent(result));
    assert.equal(module.Mode[Symbol.for("test.enum")], "trinity.Owner.Mode");
    assert.equal(module.Mode.On, module.Mode.Alias);
    assert.equal(Object.isFrozen(module.Mode), true);
    assert.deepEqual(JSON.parse(JSON.stringify(module.Mode)), {Off: 0, On: 1, Alias: 1});
    assert.equal(Object.isFrozen(module.Other), true);
});

test("refresh rejects unexpected code, declaration order, member and value drift", () =>
{
    for (const changed of [
        source + "activate();\n",
        source.replace("Off: 0", "Off: 4"),
        source.replace("Off: 0,\n  On: 1", "On: 1,\n  Off: 0"),
        source.replace("  Alias: 1,\n", ""),
        source.replace("export const Other", "export const Mode"),
        source.replace("Object.freeze({", "different({")
    ]) assert.throws(() => refreshEnumRegistrations(changed, records, registrations), mismatch);
    const canonical = refreshEnumRegistrations(source, records, registrations);
    assert.throws(() => refreshEnumRegistrations(canonical.replace("blueEnums.Create(", "blueEnums.Register("), records, registrations), mismatch);
    assert.throws(() => refreshEnumRegistrations(canonical.replace('"value": 1', '"value": 8'), records, registrations), mismatch);
    assert.throws(() => refreshEnumRegistrations(canonical, records, [{...registrations[0], definition: {}}]), mismatch);
});

test("refresh rejects missing, ambiguous or invalid registration and schema records", () =>
{
    for (const changed of [
        [], [registrations[0], registrations[0]],
        [{...registrations[0], exportName: "Absent"}],
        [{...registrations[0], name: " padded "}],
        [{...registrations[0], definition: {unknown: true}}],
        [{...registrations[0], definition: {chooser: [{name: "wrong", member: "Missing"}]}}],
        [{...registrations[0], definition: {chooser: [{name: "copied number", value: 1}]}}],
        [{...registrations[0], definition: {members: [{name: "Off", member: "On"}]}}],
        [{...registrations[0], definition: {members: [{name: "On", member: "On"}, {name: "On", member: "Alias"}]}}],
        [{...registrations[0], definition: {line: "19"}}],
        [{...registrations[0], definition: {exposure: -1}}],
        [{...registrations[0], definition: {source: null}}],
        [{...registrations[0], definition: {chooser: [{name: "On", member: "On", description: false}]}}]
    ]) assert.throws(() => refreshEnumRegistrations(source, records, changed), mismatch);
    assert.throws(() => refreshEnumRegistrations(source, [...records].reverse(), registrations), mismatch);
    assert.throws(() => refreshEnumRegistrations(source.replaceAll("Other", "blueEnums"), [records[0], {...records[1], name: "blueEnums", qualifiedName: "blueEnums"}], registrations), mismatch);
    assert.throws(() => refreshEnumRegistrations(source, records.slice(1), registrations), mismatch);
    assert.throws(() => refreshEnumRegistrations(source, [records[0], records[0]], registrations), mismatch);
    assert.throws(() => refreshEnumRegistrations(source, records, registrations, {registryImport: "\nbad"}), mismatch);
    assert.throws(() => refreshEnumRegistrations(source, [{...records[0], source: "../outside.h"}, records[1]], registrations));
});

test("chooser aliases may repeat even though members cannot repeat", () =>
{
    const repeated = [{...registrations[0], definition: {chooser: [
        {name: "same label", member: "On"}, {name: "same label", member: "Alias"}
    ]}}];
    const result = refreshEnumRegistrations(source, records, repeated);
    assert.equal((result.match(/same label/g) || []).length, 2);
});
