// Reviewed resource-address semantics for strings whose C++/Black storage cannot
// distinguish an asset address from a graph lookup or relative bank fragment.
// Keys are declaration owner + exposed member, never a Path-suffix heuristic.
// Keep authored defaults and native wire types unchanged.
const RESOURCE_PATH_MEMBERS = new Map([
    // Source: audio/src/AudManager.cpp:276
    ["AudSettings", new Set(["baseSoundbankPath"])],
    // Source: runtime/src/character/model/catalog/CjsCharacterDefinition.js
    ["CjsCharacterDefinition", new Set(["sourcePath"])],
    // Source: runtime/src/character/model/catalog/CjsCharacterMaterialProfile.js
    ["CjsCharacterMaterialProfile", new Set(["sourcePath"])],
    // Source: runtime/src/character/model/planning/CjsCharacterOrigin.js
    ["CjsCharacterOrigin", new Set(["resourcePath"])],
    // Source: runtime/src/character/model/catalog/CjsCharacterPartMetadata.js
    ["CjsCharacterPartMetadata", new Set(["sourcePath"])],
    // Source: runtime/src/character/CjsCharacterAppearanceConstruction.js:125
    // Source: runtime/src/character/CjsCharacterAppearanceConstruction.js:128
    ["CjsCharacterPartModelBundle", new Set(["configurationPath","geometryPath"])],
    // Source: runtime/src/character/model/catalog/CjsCharacterPartSource.js
    ["CjsCharacterPartSource", new Set(["sourcePath"])],
    // Source: runtime/src/character/model/catalog/CjsCharacterPartType.js
    ["CjsCharacterPartType", new Set(["sourcePath"])],
    // Source: runtime/src/character/model/resources/CjsCharacterPortraitResource.js
    ["CjsCharacterPortraitResource", new Set(["resPath"])],
    // Source: runtime/src/character/model/catalog/CjsCharacterProjectionProfile.js
    ["CjsCharacterProjectionProfile", new Set(["sourcePath","texturePath","maskPath"])],
    // Source: runtime/src/character/model/catalog/CjsCharacterRecipeProfile.js
    ["CjsCharacterRecipeProfile", new Set(["sourcePath"])],
    // Source: runtime/src/character/model/planning/CjsCharacterResolvedPart.js
    ["CjsCharacterResolvedPart", new Set(["configurationPath","geometryPath"])],
    // Source: runtime/src/character/model/resources/CjsCharacterResource.js
    ["CjsCharacterResource", new Set(["resPath"])],
    // Source: runtime/src/character/model/planning/CjsCharacterTextureAsset.js
    ["CjsCharacterTextureAsset", new Set(["uri"])],
    // Source: runtime/src/character/model/catalog/CjsCharacterTextureMetadata.js
    ["CjsCharacterTextureMetadata", new Set(["sourcePath"])],
    // Source: runtime/src/sof/EveSOF.js:2127
    ["CjsExternalRef", new Set(["resPath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2TexturedPointLight.js:95
    ["CjsLightData", new Set(["texturePath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    ["EveBannerLight", new Set(["lightProfilePath"])],
    // Source: trinity/trinity/Eve/SpaceObject/Children/EveChildInstancedMeshes.cpp:560
    ["EveChildInstancedMesh", new Set(["geometryPath"])],
    // Source: trinity/trinity/Eve/SpaceObject/Children/EveChildRef.cpp:349
    ["EveChildRef", new Set(["resPath"])],
    // Source: trinity/trinity/Eve/SpaceObject/Children/EveChildSocket.cpp:486
    ["EveChildSocket", new Set(["resPath"])],
    // Source: trinity/trinity/Eve/SpaceObject/Children/EveChildTurret.cpp:56
    // Source: trinity/trinity/Eve/SpaceObject/Children/EveChildTurret.cpp:69
    ["EveChildTurret", new Set(["firingEffectResPath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    ["EveHazeSetLight", new Set(["lightProfilePath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    ["EvePlaneLight", new Set(["lightProfilePath"])],
    // Source: runtime/src/trinity/eve/smartLights/EveSmartLightPointLight.js:299
    // Source: trinity/trinity/Eve/SpaceObject/Children/SmartLightSets/EveSmartLightPointLight.cpp:23
    // Source: trinity/trinity/Eve/SpaceObject/Children/SmartLightSets/EveSmartLightPointLight.cpp:36
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    ["EveSmartLightPointLight", new Set(["lightProfilePath"])],
    // Source: runtime/src/sof/EveSOF.js:2939
    ["EveSOF", new Set(["volumetricTrailPath"])],
    // Source: runtime/src/sof/EveSOF.js:5522
    // Source: runtime/src/sof/EveSOF.js:5523
    // Source: runtime/src/sof/EveSOF.js:5524
    ["EveSOFDataBooster", new Set(["shapeAtlasResPath","gradient0ResPath","gradient1ResPath"])],
    // Source: runtime/src/sof/EveSOF.js:1900
    ["EveSOFDataGenericDamage", new Set(["shieldGeometryResFilePath"])],
    // Source: runtime/src/sof/EveSOF.js:2357
    // Source: runtime/src/sof/EveSOF.js:2363
    // Source: runtime/src/sof/EveSOF.js:1417
    ["EveSOFDataHull", new Set(["modelRotationCurvePath","modelTranslationCurvePath","geometryResFilePath"])],
    // Source: runtime/src/sof/EveSOF.js:1993
    ["EveSOFDataHullChild", new Set(["redFilePath"])],
    // Source: runtime/src/sof/EveSOF.js:1993
    ["EveSOFDataHullChildSetItem", new Set(["redFilePath"])],
    // Source: runtime/src/sof/EveSOF.js:2341
    ["EveSOFDataHullController", new Set(["path"])],
    // Source: runtime/src/trinity/eve/lights/Tr2TexturedPointLight.js:95
    // Source: runtime/src/sof/EveSOF.js:3469
    ["EveSOFDataHullLightSetTexturedPointLight", new Set(["texturePath"])],
    // Source: runtime/src/sof/EveSOF.js:3538
    // Source: runtime/src/sof/EveSOF.js:3542
    // Source: runtime/src/sof/EveSOF.js:3546
    ["EveSOFDataHullPlaneSet", new Set(["layer1MapResPath","layer2MapResPath","maskMapResPath"])],
    // Source: runtime/src/sof/EveSOF.js:3375
    // Source: runtime/src/sof/EveSOF.js:3384
    ["EveSOFDataHullSpotlightSet", new Set(["coneTextureResPath","glowTextureResPath"])],
    // Source: runtime/src/sof/EveSOF.js:2410
    ["EveSOFDataInstancedMesh", new Set(["geometryResPath"])],
    // Source: runtime/src/sof/EveSOF.js:5576
    ["EveSOFDataMultiHullDecalIndexBuffers", new Set(["combinedGeometryResPath"])],
    // Source: runtime/src/sof/EveSOF.js:4937
    ["EveSOFDataPatternLayer", new Set(["textureResFilePath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    // Source: runtime/src/sof/EveSOF.js:3331
    ["EveSOFDataPointLightAttachment", new Set(["lightProfilePath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    // Source: runtime/src/sof/EveSOF.js:3331
    ["EveSOFDataSpotLightAttachment", new Set(["lightProfilePath"])],
    // Source: runtime/src/sof/EveSOF.js:4921
    ["EveSOFDataTexture", new Set(["resFilePath"])],
    // Source: runtime/src/trinity/eve/scene/EveSpaceScene.js:1470
    // Source: trinity/trinity/Eve/EveSpaceScene.cpp:3230
    // Source: trinity/trinity/Eve/EveSpaceScene.cpp:3307
    // Source: runtime/src/trinity/eve/scene/EveSpaceScene.js:1474
    // Source: trinity/trinity/Eve/EveSpaceScene.cpp:3234
    // Source: trinity/trinity/Eve/EveSpaceScene.cpp:3315
    // Source: runtime/src/trinity/eve/scene/EveSpaceScene.js:1478
    // Source: trinity/trinity/Eve/EveSpaceScene.cpp:3238
    // Source: trinity/trinity/Eve/EveSpaceScene.cpp:3323
    // Source: trinity/trinity/Eve/EveSpaceScene_Blue.cpp:254
    // Source: trinity/trinity/Eve/EveSpaceScene_Blue.cpp:261
    // Source: runtime/src/trinity/eve/scene/EveSpaceScene.js:1276
    // Source: runtime/src/trinity/eve/scene/EveSpaceScene.js:1453
    // Source: trinity/trinity/Eve/EveSpaceScene.cpp:3213
    // Source: trinity/trinity/Eve/EveSpaceScene.cpp:3276
    // Source: trinity/trinity/Eve/EveSpaceScene.cpp:3299
    ["EveSpaceScene", new Set(["envMap1ResPath","envMap2ResPath","envMap3ResPath","lowQualityNebulaResPath","lowQualityNebulaMixResPath","envMapResPath"])],
    // Source: trinity/trinity/Eve/UI/EveSpherePin.cpp:89
    // Source: trinity/trinity/Eve/UI/EveSpherePin.cpp:167
    // Source: trinity/trinity/Eve/UI/EveSpherePin.cpp:195
    ["EveSpherePin", new Set(["pinEffectResPath","geometryResPath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    ["EveSpotlightLight", new Set(["lightProfilePath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    ["EveSpriteLight", new Set(["lightProfilePath"])],
    // Source: runtime/src/trinity/eve/attachment/booster/EveTrailsSet.js:109
    // Source: trinity/trinity/Eve/SpaceObject/Attachments/EveTrailsSet.cpp:75
    ["EveTrailsSet", new Set(["geometryResPath"])],
    // Source: trinity/trinity/Eve/Turret/EveTurretSet_Blue.cpp:105
    // Source: runtime/src/trinity/eve/attachment/turrets/EveTurretSet.js:1194
    ["EveTurretSet", new Set(["firingEffectResPath","geometryResPath"])],
    // Source: runtime/src/trinity/controllers/action/Tr2ActionChildEffect.js:136
    // Source: trinity/trinity/Controllers/Actions/Tr2ActionChildEffect.cpp:118
    ["Tr2ActionChildEffect", new Set(["path"])],
    // Source: trinity/trinity/Controllers/Actions/Tr2ActionOverlay.cpp:148
    ["Tr2ActionOverlay", new Set(["path"])],
    // Source: trinity/trinity/Tr2AtlasTexture.cpp:194
    ["Tr2AtlasTexture", new Set(["resPath"])],
    // Source: runtime/src/trinity/controllers/Tr2ControllerReference.js:235
    // Source: trinity/trinity/Controllers/Tr2ControllerReference.cpp:16
    // Source: trinity/trinity/Controllers/Tr2ControllerReference.cpp:28
    ["Tr2ControllerReference", new Set(["path"])],
    // Source: runtime/src/trinity/shader/Tr2Effect.js:561
    // Source: runtime/src/trinity/shader/Tr2Effect.js:883
    // Source: trinity/trinity/Shader/Tr2Effect.cpp:397
    ["Tr2Effect", new Set(["effectFilePath","actualEffectFilePath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    ["Tr2FactionLight", new Set(["lightProfilePath"])],
    // Source: trinity/trinity/Shader/Parameter/Tr2GeometryBufferParameter.cpp:37
    ["Tr2GeometryBufferParameter", new Set(["resourcePath"])],
    // Source: trinity/trinity/Tr2GrannyPrimitiveSet.cpp:224
    ["Tr2GrannyPrimitiveSet", new Set(["grannyResPath"])],
    // Source: runtime/src/trinity/curves/track/Tr2GrannyTrack.js:94
    // Source: trinity/trinity/Curves/Tr2GrannyTrack.cpp:96
    ["Tr2GrannyTrack", new Set(["grannyResPath"])],
    // Source: runtime/src/trinity/core/mesh/Tr2InstancedMesh.js:111
    // Source: runtime/src/trinity/core/mesh/Tr2InstancedMesh.js:204
    // Source: trinity/trinity/Tr2InstancedMesh.cpp:67
    // Source: trinity/trinity/Tr2InstancedMesh.cpp:114
    ["Tr2InstancedMesh", new Set(["instanceGeometryResPath"])],
    // Source: runtime/src/character/incarna/interior/Tr2InteriorCell.js
    ["Tr2InteriorCell", new Set(["shProbeResPath"])],
    // Source: trinity/trinity/Interior/Tr2InteriorPlaceable.cpp:594
    ["Tr2InteriorPlaceable", new Set(["placeableResPath"])],
    // Source: trinity/trinity/Interior/Tr2InteriorScene.cpp:1399
    ["Tr2InteriorScene", new Set(["backgroundCubemapPath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    // Source: trinity/trinity/Lights/Tr2Light.cpp:170
    // Source: trinity/trinity/Lights/Tr2Light.cpp:184
    ["Tr2Light", new Set(["lightProfilePath"])],
    // Source: trinity/trinity/Tr2MaterialParameterStore.cpp:47
    ["Tr2MaterialParameterStore", new Set(["parentPath"])],
    // Source: runtime/src/trinity/core/mesh/Tr2Mesh.js:88
    // Source: runtime/src/trinity/core/mesh/Tr2Mesh.js:103
    ["Tr2Mesh", new Set(["geometryResPath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    ["Tr2PointLight", new Set(["lightProfilePath"])],
    // Source: runtime/src/trinity/postProcess/Tr2PostProcessAttributes.js:1133
    // Source: runtime/src/trinity/postProcess/Tr2PostProcessAttributes.js:1195
    // Source: runtime/src/trinity/postProcess/Tr2PostProcessAttributes.js:1175
    // Source: runtime/src/trinity/postProcess/Tr2PostProcessAttributes.js:1176
    ["Tr2PostProcessAttributes", new Set(["grimePath","lutPath","vignetteShapePath","vignetteDetailPath"])],
    // Source: runtime/src/trinity/postProcess/Tr2PostProcessRenderer.js:1692
    ["Tr2PPBloomEffect", new Set(["grimePath"])],
    // Source: runtime/src/trinity/postProcess/Tr2PostProcessRenderer.js:1006
    ["Tr2PPGodRaysEffect", new Set(["noiseTexturePath"])],
    // Source: runtime/src/trinity/postProcess/Tr2PostProcessRenderer.js:1777
    ["Tr2PPLutEffect", new Set(["path"])],
    // Source: runtime/src/trinity/postProcess/Tr2PostProcessRenderer.js:1731
    // Source: runtime/src/trinity/postProcess/Tr2PostProcessRenderer.js:1730
    ["Tr2PPVignetteEffect", new Set(["detailPath","shapePath"])],
    // Source: trinity/trinity/Tr2SkinnedModel.cpp:218
    ["Tr2SkinnedModel", new Set(["geometryResPath"])],
    // Source: runtime/src/trinity/eve/lights/Tr2Light.js:325
    ["Tr2SpotLight", new Set(["lightProfilePath"])],
    // Source: trinity/trinity/Particle/Tr2StaticEmitter.cpp:39
    // Source: trinity/trinity/Particle/Tr2StaticEmitter.cpp:64
    ["Tr2StaticEmitter", new Set(["geometryResourcePath"])],
    // Source: runtime/src/trinity/core/animation/Tr2TextureAnimation.js:127
    // Source: runtime/src/trinity/core/animation/Tr2TextureAnimation.js:404
    ["Tr2TextureAnimation", new Set(["resPath"])],
    // Source: trinity/trinity/Lights/Tr2TexturedPointLight.cpp:20
    // Source: runtime/src/trinity/eve/lights/Tr2TexturedPointLight.js:95
    ["Tr2TexturedPointLight", new Set(["texturePath"])],
    // Source: trinity/trinity/Shader/Parameter/TriTextureParameter.cpp:232
    ["TriTextureParameter", new Set(["resourcePath"])],
]);

/** Whether an explicitly reviewed string member names a resource address. */
export function isResourcePathMember(className, memberName)
{
    return RESOURCE_PATH_MEMBERS.get(className)?.has(memberName) === true;
}
